import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#00343e",
        "inverse-on-surface": "#4f5469",
        "on-primary": "#004b58",
        "outline-variant": "#41475b",
        "primary-dim": "#40ceed",
        "surface-container-high": "#171f36",
        "background": "#070d1f",
        "secondary": "#ec63ff",
        "tertiary-container": "#8f60fa",
        "on-background": "#dfe4fe",
        "surface-container-lowest": "#000000",
        "surface": "#070d1f",
        "inverse-primary": "#00687b",
        "on-primary-fixed-variant": "#005564",
        "error-dim": "#d7383b",
        "on-surface-variant": "#a5aac2",
        "on-tertiary-container": "#000000",
        "primary": "#53ddfc",
        "secondary-container": "#a200ba",
        "surface-bright": "#222b47",
        "secondary-dim": "#ec63ff",
        "on-tertiary-fixed": "#1f0052",
        "surface-tint": "#53ddfc",
        "primary-fixed": "#53ddfc",
        "on-tertiary": "#280067",
        "error-container": "#9f0519",
        "on-secondary-container": "#fff5fa",
        "tertiary-fixed": "#bda2ff",
        "on-error-container": "#ffa8a3",
        "on-secondary-fixed-variant": "#8c00a0",
        "surface-container-highest": "#1c253e",
        "on-secondary": "#3d0047",
        "tertiary-dim": "#8455ef",
        "surface-container": "#11192e",
        "on-error": "#490006",
        "surface-container-low": "#0c1326",
        "primary-fixed-dim": "#40ceed",
        "on-secondary-fixed": "#5e006c",
        "secondary-fixed-dim": "#faa6ff",
        "tertiary-fixed-dim": "#b091ff",
        "surface-dim": "#070d1f",
        "surface-variant": "#1c253e",
        "tertiary": "#ac8aff",
        "inverse-surface": "#faf8ff",
        "secondary-fixed": "#fdbcff",
        "outline": "#6f758b",
        "error": "#ff716c",
        "primary-container": "#21bedc",
        "on-surface": "#dfe4fe",
        "on-tertiary-fixed-variant": "#4600a8",
        "on-primary-fixed": "#003640"
      },
      fontFamily: {
        "headline": ["var(--font-headline)", "Space Grotesk", "sans-serif"],
        "body": ["var(--font-body)", "Plus Jakarta Sans", "sans-serif"],
        "label": ["var(--font-label)", "Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}

export default config 